### ISSUE TITLE
建议增加 “复制笔记内部链接功能”

### ISSUE THREAD

**Issue by altairwei** [restran/wiz-search#2]
看到你的这个项目我才意识到 WizQTClient 没有本地全文搜索。我检查了下源代码发现 WizSearch.cpp 文件只有标题、创建时间之类的搜索功能，真是遗憾。

我尝试部署并运行了这个工具，在解决几个问题后开启了一个 pull request 。

在使用过程中我发现一些可以增强的地方，比如 markdown 文件的渲染功能。

解决这个问题最简单的方式是增加 “复制笔记内部链接” 功能，非常简单，参考 `src/share/WizMisc.cpp` ：

```cpp
QString WizNoteToWizKMURL(const WIZDOCUMENTDATA& document)
{
    WizDatabase& db = WizDatabaseManager::instance()->db(document.strKbGUID);
    //
    if (!db.isGroup())
    {
        return WizFormatString3("wiz://open_document?guid=%1&kbguid=%2&private_kbguid=%3", document.strGUID, "", db.kbGUID());
    }
    else
    {
        return WizFormatString2("wiz://open_document?guid=%1&kbguid=%2", document.strGUID, document.strKbGUID);
    }
    return QString();
}
```

参考以上代码构建一个 URL ，用户复制后直接粘贴入为知笔记的搜索框就能打开该笔记。

**Comment by restran** [comment]
已添加，新增一个链接“在为知中打开”，点击链接自动跳转到为知笔记客户端，并打开对应的笔记。

**Comment by altairwei** [comment]
你在 Mac 上点击链接可以直接跳转为知吗？

看来 Mac 版本客户端在系统中注册了 wiz 协议，我用 Linux 没法直接从浏览器跳转。

**Comment by restran** [comment]
我在 Mac 下可以直接跳转，没试过 Linux。
